### ISSUE TITLE
Card Faming Fehler

### ISSUE THREAD

**Issue by FireLostBoy-Tech** [zevnda/steam-game-idler#52]
### Describe the issue

https://github.com/user-attachments/assets/ff89a46f-bb22-4ef1-bec2-8bb2d7027c73
[log.txt](https://github.com/user-attachments/files/18213948/log.txt)

Wie es im Video sieht starte ich grade den Funktion Card Farming und es dauert dann nur 1-3 sec und dann ist es fertig und wenn ich dann im Steam oder logs gucke steht das es 0 Karten gefunden hat. Trotz dass das Spiel Sammelkarten besitzt 

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Pre-report checklist

- [X] I have checked for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues?q=)
- [X] I have checked the [FAQ wiki](https://github.com/zevnda/steam-game-idler/wiki/faq) for my issue
- [X] I have included my "log.txt" file located in "C:\\Users\\your_username\\AppData\\Roaming\\steam-game-idler"

**Comment by zevnda** [comment]
Have you already received all available card drops for those games? You can verify that you still have card drops by doing the following

1. Go to our Steam profile
2. Click on 'Badges'
3. Scroll down, or press `CTRL + F` to search for the game's title
4. In the top-right of the game card, you will see either X card drops remaining or no card drops remaining

**Comment by FireLostBoy-Tech** [comment]
Ich habe grade geguckt ob das daran liegt und scheinbar tut es nicht.
Ich habe auf meinem Account Atomic Heart null Spielstunden und hab das bis jz nicht angerührt.
Hab es mal damit getestet und es geht immer noch nicht

**Comment by zevnda** [comment]
If you have multiple accounts and you are switching between them, then you need to update your card farming credentials each time you switch accounts. The account you're logged in to SGI with and the account you get the cookies for must match. I've actually added a check for this in an unreleased beta version to stop confusion.

If that doesn't solve your issue, take a look at [this section of the FAQ wiki](https://github.com/zevnda/steam-game-idler/wiki/faq#:~:text=Why%20am%20I%20not%20getting%20any%20card%20drops%3F) to see if one of them might be the issue

**Comment by zevnda** [comment]
Hey mate, just following up on this issue.

Think I might know why you might be having it. Is your Steam primary language set to German or any language other than English by any chance? If so, I think the issue is that SGI is fetching the badges pages to see you games with card drops remaining but it is expecting and English version.

Can you try the following

1. Sign in to your Steam account in the browser and go to https://store.steampowered.com/account/languagepreferences
2. Change `primary language` to `English` 
3. Uncheck all options for `secondary language`
4. Uncheck all options for `additional game content languages` 
5. Save these changes, then sign out of Steam in the browser, and sign back in.
6. Get your new cookies and try to validate them in SGI

Let me know how you go.

**Comment by zevnda** [comment]
[v1.6.0](https://github.com/zevnda/steam-game-idler/releases/tag/1.6.0) should hopefully fix this issue. Let me know if it doesn't.
